name: Run Notebook Daily

on:
  schedule:
    - cron: '5 0 * * *'  # Runs daily at 8 AM UTC
  workflow_dispatch:     # Adds a manual run button

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Papermill
      run: |
        pip install papermill

    - name: Run notebook
      run: |
        papermill your_notebook_name.ipynb output.ipynb
